### ISSUE TITLE
using Saxon EE

### ISSUE THREAD

**Issue by lionelmoi** [eerohele/saxon-gradle#3]
Hi !

Thanks a lot for this plugin, this is great work !

I would like to use my own Saxon EE version (some XSLT 3.0 features like Text Value Templates do not seem to work with the plugin).

How may I go about doing this ?

**Comment by eerohele** [comment]
Thanks for the interest, I'm happy if you find the plugin useful!

The plugin will use the first version Saxon it finds in your classpath, so I think the easiest way to do it is to add this to the top of your `build.gradle`:

``` groovy
buildscript {
    dependencies {
        // Modify the path to point to your Saxon-EE JAR file.
        classpath files('/opt/saxon/saxon9ee.jar')
    }
}
```

That should do it. If it doesn't work, please let me know and I'll look into it.

Oh, if you use [the Gradle Daemon](https://docs.gradle.org/2.5/userguide/gradle_daemon.html), you might need to run `gradle --stop` once after that for the changes to take effect.

Also, if you use [a Saxon configuration file](http://saxonica.com/html/documentation/configuration/configuration-file/), make sure the `@edition` attribute in it says `EE`:

``` xml
<configuration xmlns="http://saxon.sf.net/ns/configuration" edition="EE">
  <xslt
     version="3.0"
     >
  </xslt>

  ...

</configuration>
```

Otherwise you won't be able to use any of the EE features.

Please let me know whether that works for you.

**Comment by eerohele** [comment]
I hope you got it to work. I'll close this issue for now, but please feel free to ask further questions if anything comes up.

**Comment by lionelmoi** [comment]
Sorry I did not answer sooner,

Your fix worked :)
